# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.model.work_monitoring_service:
        class: AppBundle\Model\WorkMonitoringService
        arguments: ["@umbrella.worksnaps"]

    app.view.telegram_viewer:
        class: AppBundle\View\TelegramViewer
        arguments: ["shaygan.telegram_bot_api"]
